using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

/// <summary>
/// PoolListSO의 내용을 그대로 PoolType.cs로 뽑아낸다.
/// enum 값은 PoolItem.Id를 그대로 쓰므로, 항목 순서를 바꾸거나 이름을 고쳐도
/// 이미 저장된 PoolType 필드(프리셋 등)는 그대로 유지된다.
/// </summary>
public static class PoolEnumGenerator
{
    public const string EnumFileName = "PoolType.cs";
    private const string FallbackPath = "Assets/01.Scripts/Core/ObjectPool/PoolType.cs";

    private static readonly HashSet<string> Keywords = new(
        ("abstract as base bool break byte case catch char checked class const continue decimal default delegate " +
         "do double else enum event explicit extern false finally fixed float for foreach goto if implicit in int " +
         "interface internal is lock long namespace new null object operator out override params private protected " +
         "public readonly ref return sbyte sealed short sizeof stackalloc static string struct switch this throw " +
         "true try typeof uint ulong unchecked unsafe ushort using virtual void volatile while")
        .Split(' '));

    /// <summary>임의의 문자열을 enum 멤버로 쓸 수 있는 형태로 다듬는다.</summary>
    public static string Sanitize(string raw)
    {
        if (string.IsNullOrEmpty(raw)) return string.Empty;

        StringBuilder builder = new();
        foreach (char c in raw)
        {
            if (char.IsLetterOrDigit(c) || c == '_')
                builder.Append(c);
            else if (builder.Length > 0 && builder[builder.Length - 1] != '_')
                builder.Append('_');
        }

        string result = builder.ToString().Trim('_');
        if (result.Length == 0) return string.Empty;

        if (char.IsDigit(result[0]))
            result = "_" + result;

        if (Keywords.Contains(result))
            result += "_";

        return result;
    }

    public static bool IsValidName(string name)
        => !string.IsNullOrEmpty(name) && Sanitize(name) == name;

    public static string BuildSource(PoolListSO list)
    {
        StringBuilder builder = new();
        builder.AppendLine("//------------------------------------------------------------------------------");
        builder.AppendLine("// <auto-generated>");
        builder.AppendLine("//     Tools > Pool Manager 창의 Generate Enum 버튼으로 생성되는 파일입니다.");
        builder.AppendLine("//     직접 수정하면 다음 생성 때 덮어써집니다.");
        builder.AppendLine("// </auto-generated>");
        builder.AppendLine("//------------------------------------------------------------------------------");
        builder.AppendLine();
        builder.AppendLine("public enum PoolType");
        builder.AppendLine("{");
        builder.AppendLine("    None = 0,");

        if (list != null)
        {
            foreach (PoolGroup group in list.Groups)
            {
                bool headerWritten = false;

                foreach (PoolItem item in group.Items)
                {
                    if (!item.IsValid || !IsValidName(item.EnumName)) continue;

                    if (!headerWritten)
                    {
                        builder.AppendLine();
                        builder.AppendLine($"    // {group.Name}");
                        headerWritten = true;
                    }

                    builder.AppendLine($"    {item.EnumName} = {item.Id},");
                }
            }
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    public static bool IsUpToDate(PoolListSO list)
    {
        string path = FindPath();
        if (!File.Exists(path)) return false;

        return Normalize(File.ReadAllText(path)) == Normalize(BuildSource(list));
    }

    public static void Generate(PoolListSO list)
    {
        string path = FindPath();
        File.WriteAllText(path, BuildSource(list));

        AssetDatabase.ImportAsset(path, ImportAssetOptions.ForceUpdate);
        Debug.Log($"[PoolEnumGenerator] {path} 를 생성했습니다.");
    }

    public static string FindPath()
    {
        foreach (string guid in AssetDatabase.FindAssets("PoolType t:MonoScript"))
        {
            string path = AssetDatabase.GUIDToAssetPath(guid);
            if (Path.GetFileName(path) == EnumFileName)
                return path;
        }

        return FallbackPath;
    }

    private static string Normalize(string text) => text.Replace("\r\n", "\n").Trim();
}
